### ISSUE TITLE
How to edit the custom lorems and add my own text?

### ISSUE THREAD

**Issue by aderchox** [jobe451/vscode-lorem-whatever#3]
I'm trying to add my own text and use it when I choose "custom 1", is that possible? I've tried to find it using vscode auto completion, and something like this is suggested:
    "loremWhatever.defaultLorem":"Custom 1"
However, the value is already filled with the title "Custom 1". I don't know where I have to put my own text. Thank you in advance.

**Comment by jobe451** [comment]
go to the settings json:
![image](https://user-images.githubusercontent.com/910027/74143457-1fc37880-4bfb-11ea-9fed-821ee2cc2218.png)

then:
![image](https://user-images.githubusercontent.com/910027/74143694-8d6fa480-4bfb-11ea-97dc-ce0b9be9591e.png)
